# Generated by Django 5.1.1 on 2024-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('hdfc', 'HDFC'), ('icici', 'ICICI')], max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('booking_or_refund', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('extracted_data', models.JSONField()),
            ],
        ),
    ]
